THE NEKOCENSE LICENSE, VERSION 1.0

Effective Date: August 24, 2025

Licensor: NekoMimiOfficial

WHEREAS, Licensor is the proprietor of certain proprietary software and associated intellectual property (hereinafter, the "Work");

WHEREAS, Licensor desires to permit the use, reproduction, modification, and distribution of the Work under specific, highly controlled terms and conditions;

WHEREAS, Licensee (hereinafter, "You" or "Your") desires to obtain a license to the Work subject to the limitations and obligations set forth herein;

NOW, THEREFORE, in consideration of the mutual covenants and agreements contained herein, the parties agree as follows:

1. DEFINITIONS
1.1. "License" shall mean the entirety of the terms and conditions governing the use, reproduction, and distribution of the Work as stipulated in this document.
1.2. "Licensor" shall mean the legal entity or individual holding the copyright to the Work, or any authorized entity acting on behalf of such copyright holder, that grants permissions under this License.
1.3. "You" (or "Your") shall mean any individual or Legal Entity exercising the permissions granted by this License.
1.4. "Legal Entity" shall mean the collective union of the acting entity and all other entities that are under common control with, control, or are controlled by that acting entity. For the express purposes of this definition, "control" denotes (i) the direct or indirect power to direct or cause the direction of the management and policies of such entity, whether by contract, equity ownership, or otherwise; or (ii) beneficial ownership of fifty percent (50%) or more of the outstanding voting shares or other ownership interests of such entity.
1.5. "Contributor" shall mean any individual or Legal Entity that has furnished a Contribution to the Licensor, and whose Contribution has subsequently been incorporated into the Work.
1.6. "Contribution" shall mean any original work of authorship, including, but not limited to, the initial version of the Work, and any subsequent modifications, enhancements, or additions thereto, or Derivative Works thereof, that is intentionally submitted to the Licensor for inclusion within the Work by the copyright owner of such material or by an individual or Legal Entity duly authorized to submit on behalf of such copyright owner.
1.7. "Derivative Works" shall mean any work, irrespective of its form (whether Source or Object), that is based upon, adapted from, or otherwise derived from the Work, and for which the editorial revisions, annotations, elaborations, or other modifications, when considered as a whole, constitute an original work of authorship. For the avoidance of doubt, Derivative Works shall explicitly exclude works that remain logically separable from, or merely link to (or bind by name to the interfaces of), the Work and its Derivative Works.
1.8. "Source" form shall denote the preferred embodiment for undertaking modifications, including, without limitation, software source code, documentation source files, and configuration files.
1.9. "Object" form shall denote any embodiment resulting from the mechanical transformation or translation of a Source form, including, without limitation, compiled object code, machine-readable code, generated documentation, and conversions to alternative media types.
1.10. "Monetize" or "Earn Money" shall mean the act of obtaining, acquiring, or generating financial gain, profit, commercial advantage, or pecuniary benefit from the Work or any Derivative Works, whether directly or indirectly. This comprehensive definition explicitly includes, but is not restricted to, the sale of the Work or Derivative Works, the imposition of charges for services directly or indirectly associated with the Work (e.g., technical support, hosting, consulting services), the bundling or integration of the Work with other commercial products or services, the receipt of advertising revenue directly attributable to the Work, or the utilization of the Work to furnish a for-profit service to any third party. For clarity, this definition specifically excludes the acceptance of voluntary, non-recurring financial contributions (e.g., donations) from individuals or entities that are demonstrably not deriving direct financial profit from their use of the Work itself.

2. GRANT OF COPYRIGHT LICENSE
2.1. Subject to the full and strict adherence to all terms and conditions stipulated in this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, royalty-free, irrevocable copyright license, without charge, to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in both Source and Object form. Notwithstanding the foregoing, You are hereby expressly and unequivocally prohibited from engaging in any act to Monetize or Earn Money from the Work or any Derivative Works thereof, in any shape, manner, or form, whether directly or indirectly.

3. GRANT OF PATENT LICENSE
3.1. No patent license, whether express, implied, or by estoppel, is granted under this License. All patent rights held by the Licensor or any Contributor remain fully reserved.

4. REDISTRIBUTION
4.1. You are permitted to reproduce and distribute copies of the Work or Derivative Works thereof in any tangible or intangible medium, with or without modifications, and in either Source or Object form, provided that You satisfy, in full, the following mandatory conditions:
 * a. You shall furnish any and all recipients of the Work or Derivative Works with a complete and unaltered copy of this License; and
 * b. You shall ensure that any modified files prominently display notices indicating that You have altered said files; and
 * c. You shall retain, within the Source form of any Derivative Works that You distribute, all copyright and attribution notices from the Source form of the Work, excluding only those notices that are demonstrably not pertinent to any constituent part of the Derivative Works; and
 * d. In the event that the Work includes a "NOTICE" text file as an integral component of its distribution, then any Derivative Works that You distribute shall include a legible copy of the attribution notices contained within such NOTICE file, excluding only those notices that are demonstrably not pertinent to any constituent part of the Derivative Works, in a minimum of one of the following locations: embedded within a NOTICE text file distributed contemporaneously with the Derivative Works; within the Source form or accompanying documentation, if such are provided alongside the Derivative Works; or, within a display generated by the Derivative Works, if and where such third-party notices customarily appear. The content of the NOTICE file is provided for informational purposes solely and shall in no way operate to modify the terms or conditions of this License. You are permitted to append Your own attribution notices within Derivative Works that You distribute, either alongside or as an addendum to the NOTICE text derived from the Work, provided always that such additional attribution notices shall not be construed or interpreted as modifying the operative terms of this License.
 * e. You explicitly acknowledge, confirm, and agree that any and all redistribution of the Work or Derivative Works shall be strictly subject to the "no monetization" clause as precisely defined in Section 2 herein. You are explicitly prohibited from distributing the Work or Derivative Works to any party if such distribution directly or indirectly results in, or facilitates, the Monetization or Earning of Money by You or by the recipient from the Work or Derivative Works.

5. SUBMISSION OF CONTRIBUTIONS
5.1. Unless You explicitly declare otherwise in writing, any Contribution intentionally submitted by You to the Licensor for inclusion in the Work shall be deemed submitted under the terms and conditions of this License, without the imposition of any additional or superseding terms or conditions. Notwithstanding the foregoing, nothing contained herein shall be construed to supersede or modify the terms of any separate, distinct license agreement You may have formally executed with the Licensor pertaining to such Contributions.

6. TRADEMARKS
6.1. This License confers no permission whatsoever to utilize the trade names, trademarks, service marks, or product names of the Licensor, save and except as is strictly required for the reasonable and customary description of the origin of the Work and for the accurate reproduction of the content contained within the NOTICE file.

7. DISCLAIMER OF WARRANTY
7.1. EXCEPT AS MANDATED BY APPLICABLE STATUTORY LAW OR AS EXPLICITLY AGREED UPON IN A SEPARATE WRITTEN INSTRUMENT, THE LICENSOR PROVIDES THE WORK (AND EACH CONTRIBUTOR PROVIDES ITS RESPECTIVE CONTRIBUTIONS) ON AN "AS IS" BASIS. THIS PROVISION IS MADE WITHOUT ANY WARRANTIES OR CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. YOU ASSUME SOLE RESPONSIBILITY FOR DETERMINING THE SUITABILITY AND APPROPRIATENESS OF USING OR REDISTRIBUTING THE WORK AND SHALL BEAR ANY AND ALL RISKS ASSOCIATED WITH YOUR EXERCISE OF THE PERMISSIONS GRANTED UNDER THIS LICENSE.

8. LIMITATION OF LIABILITY
8.1. IN NO EVENT AND UNDER NO LEGAL THEORY, WHETHER ARISING IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE, UNLESS STRICTLY REQUIRED BY APPLICABLE LAW (SUCH AS FOR DELIBERATE AND GROSSLY NEGLIGENT ACTS) OR AS EXPRESSLY AGREED UPON IN WRITING, SHALL ANY CONTRIBUTOR BE LIABLE TO YOU FOR DAMAGES OF ANY CHARACTER. THIS INCLUDES, BUT IS NOT LIMITED TO, DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY NATURE WHATSOEVER, ARISING AS A RESULT OF THIS LICENSE OR OUT OF THE USE OR INABILITY TO USE THE WORK (INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER COMMERCIAL DAMAGES OR LOSSES), EVEN IF SUCH CONTRIBUTOR HAS BEEN APPRISED OF THE POTENTIAL FOR SUCH DAMAGES.

9. ACCEPTING WARRANTY OR ADDITIONAL LIABILITY
9.1. In the course of redistributing the Work or Derivative Works thereof, You may elect to offer, and impose a fee for, the acceptance of supplementary support, warranty, indemnity, or other liability obligations and/or rights, provided such offerings are fully consistent with the provisions of this License. However, in accepting any such obligations, You shall act solely on Your own behalf and assume full and exclusive responsibility. You shall not, under any circumstances, act on behalf of any other Contributor, and such actions shall only be undertaken if You explicitly agree to indemnify, defend, and hold each Contributor harmless from and against any and all liability incurred by, or claims asserted against, such Contributor by virtue of Your acceptance of any such additional warranty or liability.
